import { CitizenDto, EducationDto, EthnicityDto, GenderDto, HandicapDto, NameSuffixDto, RaceDto, StatesDto, VeteranDto, WithHoldingDto } from "../claim/createclaim/createclaim.component";

export interface DataItem {
  email: string;
  socialSecurityNumber: string;
  dateOfBirth: string;
  telephoneNumber: string;
  gender: string;
  genderCode: string;
  occupation: string;
  mailingAddress: string;
  claimantFirstName: string;
  claimantMiddleName: string;
  claimantLastName: string;
  claimantSuffix: string;
  authorizedAlienNumber: string;
  mailingStreetAddress: string;
  mailingCity: string;
  mailingState: string;
  mailingStateCode: string;
  zipCode: string;
  handicap: string;
  veteranStatus: string;
  race: string;
  ethnicity: string;
  federalwithHolding: string;
  citizen: string;
  education: string;
  validation: boolean;
  states: StatesDto[];
  races: RaceDto[];
  veterans: VeteranDto[];
  withholdings: WithHoldingDto[];
  namesuffixs: NameSuffixDto[];
  handicaps: HandicapDto[];
  genders: GenderDto[];
  ethnicityList: EthnicityDto[];
  citizens: CitizenDto[];
  educations: EducationDto[];
};